container: "docker://continuumio/miniconda3"
configfile: "config/config_main.yaml"
include: "rules/common.smk"


rule targets:
    input:
        # expand(
        #     os.path.join(
        #     config['output_folder'],
        #     "vcfs",
        #     "{patient}.unfiltered.vcf"
        # ),
        #         patient=patients,
        # )
        # # expand(
        # #     os.path.join(
        # #         config["output_folder"],
        # #         "qc",
        # #         "{patient}.{sample_type}.recal_data.table"
        # #     ), patient=patients, sample_type="tumor"
        # # )
        vcf=expand(
           config['output_folder']
           + "vcfs/{patient}.vep.vcf.gz",
           patient=patients
           ),
        idx=expand(
           config['output_folder']
           + "vcfs/{patient}.vep.vcf.gz.tbi",
           patient=patients
           )

include: "rules/alignment.smk"
include: "rules/preprocessing.smk"
include: "rules/somatic.smk"
