# One between ["WES", "WGS"]
sequencing_type: "WES"
tumor_only: true
viral_integrated: true
virus_name: "MCPyV"

# PATH to relevant files
units: "units.csv"
patients: "patients.csv"

# DIRECTIVES
output_folder: "/CTGlab/projects/mcc_analysis/output/"
tmp_dir: "/CTGlab/projects/mcc_analysis/temp_gatk"
log_folder: "/CTGlab/projects/mcc_analysis/logs/"

# RESOURCES
resources:
  assembly: "GRCh38"
  genomic_regions: "/CTGlab/projects/mcc_analysis/hg38_exome_v2.0.2_targets_sorted_validated.re_annotated.bed"
  viral_genome: "/CTGlab/projects/mcc_analysis/MPCyV_genome.fa"
  reference_fasta: "/CTGlab/db/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta"
  dbsnps: "/CTGlab/db/VCF_resources/dbsnp_146.hg38.vcf.gz"
  known-indels: "/CTGlab/db/VCF_resources/Homo_sapiens_assembly38.known_indels.vcf.gz"
  1000g: "/CTGlab/db/VCF_resources/1000G_phase1.snps.high_confidence.hg38.vcf.gz"
  gnomad: "/CTGlab/db/VCF_resources/af-only-gnomad.hg38.vcf.gz"
  contamination: "/CTGlab/db/VCF_resources/small_exac_common_3.hg38.vcf.gz"
  PoN: "/CTGlab/db/VCF_resources/1000g_pon.hg38.vcf.gz"
  vep_cache: "/CTGlab/db/VCF_resources/vep_cache"


# CONTAINERS
containers:
  ctgflow_core: "docker://danilotat/ctgflow_core"
  qc: ""
  deepvariant: "docker://google/deepvariant:1.8.0"
  deepsomatic: "docker://google/deepsomatic:1.8.0"

# PARAMS
params:
  mutect2:
    num_workers: 10
    args: --max-population-af 0.05 --genotype-germline-sites --linked-de-bruijn-graph --dont-use-soft-clipped-bases
    filtering: --max-events-in-region 4 --unique-alt-read-count 2 --min-reads-per-strand 1 --min-allele-fraction 0.001
  vep:
    assembly: "GRCh38"
    threads: 4
    extra: "--pick --af --check_existing --coding_only --format vcf --vcf --symbol --terms SO --no_intergenic --tsl"

      
